In [2]:
import pandas as pd
import numpy as np

In [4]:
df_raw = pd.read_csv("ChemBL_raw.csv", delimiter=";")
df_raw.head()

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL1084787,NaN,NaN,274.39,0.0,3.06,223,c1ccc(-c2nnc(NCN3CCCCC3)s2)cc1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,54000.0
1,CHEMBL1084788,NaN,NaN,269.35,0.0,2.39,224,c1ccc(-c2cnc(NCN3CCCCC3)nn2)cc1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,60000.0
2,CHEMBL1082434,NaN,NaN,351.45,0.0,4.29,228,O=C(CCC1CCN(Cc2ccccc2)CC1)c1ccc2c(c1)OCO2,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,30.0
3,CHEMBL1084790,NaN,NaN,361.49,0.0,4.75,231,Cc1nc2cc(C(=O)CCC3CCN(Cc4ccccc4)CC3)ccc2[nH]1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,12.0
4,CHEMBL102142,NaN,NaN,385.53,0.0,2.75,234,Cc1ccc(C(=O)NC(=S)NCCOCCN(C)Cc2ccccc2)cc1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,77.0

In [7]:
df_raw.columns

Index(['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase',
       'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key',
       'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment',
       'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE',
       'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate',
       'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID',
       'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID',
       'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction',
       'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation',
       'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type',
       'Document ChEMBL ID', 'Source ID', 'Source Description',
       'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties',
       'Action Type', 'Standard Text Value', 'Value'],
      dtype='object')

In [9]:
df_select = df_raw[['Molecule ChEMBL ID', 'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Assay ChEMBL ID']]
df_select.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Relation,Standard Value,Standard Units,pChEMBL Value,Assay ChEMBL ID
0,CHEMBL1084787,c1ccc(-c2nnc(NCN3CCCCC3)s2)cc1,IC50,'=',54000.0,nM,4.27,CHEMBL1119333
1,CHEMBL1084788,c1ccc(-c2cnc(NCN3CCCCC3)nn2)cc1,IC50,'=',60000.0,nM,4.22,CHEMBL1119333
2,CHEMBL1082434,O=C(CCC1CCN(Cc2ccccc2)CC1)c1ccc2c(c1)OCO2,IC50,'=',30.0,nM,7.52,CHEMBL1119333
3,CHEMBL1084790,Cc1nc2cc(C(=O)CCC3CCN(Cc4ccccc4)CC3)ccc2[nH]1,IC50,'=',12.0,nM,7.92,CHEMBL1119333
4,CHEMBL102142,Cc1ccc(C(=O)NC(=S)NCCOCCN(C)Cc2ccccc2)cc1,IC50,'=',77.0,nM,7.11,CHEMBL1119333

In [16]:
new_names = ["molecule_chembl_id", "canonical_smiles", "standard_type", "standard_relation", "standard_value", "standard_units", "pchembl_value", "assay_chembl_id"]
df_select.columns = new_names
df_select.head()

,molecule_chembl_id,canonical_smiles,standard_type,standard_relation,standard_value,standard_units,pchembl_value,assay_chembl_id
0,CHEMBL1084787,c1ccc(-c2nnc(NCN3CCCCC3)s2)cc1,IC50,'=',54000.0,nM,4.27,CHEMBL1119333
1,CHEMBL1084788,c1ccc(-c2cnc(NCN3CCCCC3)nn2)cc1,IC50,'=',60000.0,nM,4.22,CHEMBL1119333
2,CHEMBL1082434,O=C(CCC1CCN(Cc2ccccc2)CC1)c1ccc2c(c1)OCO2,IC50,'=',30.0,nM,7.52,CHEMBL1119333
3,CHEMBL1084790,Cc1nc2cc(C(=O)CCC3CCN(Cc4ccccc4)CC3)ccc2[nH]1,IC50,'=',12.0,nM,7.92,CHEMBL1119333
4,CHEMBL102142,Cc1ccc(C(=O)NC(=S)NCCOCCN(C)Cc2ccccc2)cc1,IC50,'=',77.0,nM,7.11,CHEMBL1119333

In [11]:
df_select.to_csv("ache_activities.csv", index=False)

In [22]:
df_select.isna().any()

molecule_chembl_id    False
canonical_smiles       True
standard_type         False
standard_relation     False
standard_value        False
standard_units        False
pchembl_value         False
assay_chembl_id       False
dtype: bool

In [23]:
df_sample = df_select.sample(n=10)
df_sample

,molecule_chembl_id,canonical_smiles,standard_type,standard_relation,standard_value,standard_units,pchembl_value,assay_chembl_id
1004,CHEMBL1085280,C[n+]1c(-c2ccccc2)cn2cc(C(N)=O)ccc21.[I-],IC50,'=',9500.00,nM,5.02,CHEMBL1119333
2723,CHEMBL300170,COc1ccc(C(=O)CCc2ccc([N+](C)(C)Cc3ccccc3)cc2)c...,IC50,'=',1300.00,nM,5.89,CHEMBL645004
3278,CHEMBL4758460,COc1ccc2cc3[n+](cc2c1OCc1cccc(C)c1)CCc1cc2c(cc...,IC50,'=',7300.00,nM,5.14,CHEMBL4708697
5719,CHEMBL3939015,CC1=C(C(=O)OC(C)C)C(c2ccccc2F)c2c(nc3c(c2N)CC(...,IC50,'=',1377.00,nM,5.86,CHEMBL3888161
2829,CHEMBL1929421,C#CCN(C)Cc1cc2cc(OCCCC3CCN(Cc4ccccc4)CC3)ccc2n1C,IC50,'=',3400.00,nM,5.47,CHEMBL3413435
2698,CHEMBL3752119,COc1cccc2cc(C(=O)NCCCCCCNc3c4c(nc5ccccc35)CCCC...,IC50,'=',32.30,nM,7.49,CHEMBL3758061
6939,CHEMBL5182803,O=C(COc1ccc(CCc2ccccc2)cc1)NCC1CCN(Cc2ccccc2)CC1,IC50,'=',135.00,nM,6.87,CHEMBL5122937
3764,CHEMBL4779514,CCN(CC)C(=O)Oc1ccc(/C=C/C(=O)N2CCc3ccccc3C2)cc1OC,IC50,'=',15700.00,nM,4.80,CHEMBL4686681
1115,CHEMBL3597006,COC(=O)C1=C(Nc2ccc(Cl)cc2)C[C@@H](c2ccc(C)cc2)...,IC50,'=',2147.83,nM,5.67,CHEMBL3599183
70,CHEMBL2234836,CCOC(=O)C1=C(C)Oc2nc3c(c(N)c2[C@H]1c1ccc(OC)c(...,IC50,'=',26915.35,nM,4.57,CHEMBL3047076